/**
 * @skyra/qr — render/svg.ts
 * Deterministic SVG string generator for QRCodeMatrix.
 */
import { QRCodeMatrix, QRCodeSVGOptions } from '../types';

/**
 * Escapes characters for XML attributes.
 */
function escapeXml(unsafe: string): string {
  return unsafe.replace(/[<>&'"]/g, (c) => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '\'': return '&apos;';
      case '"': return '&quot;';
      default: return c;
    }
  });
}

/**
 * Generates an SVG path string for the dark modules.
 * @param matrix The QRCodeMatrix.
 * @param margin The quiet zone margin to apply.
 */
export function buildSVGPath(matrix: QRCodeMatrix, margin: number = 0): string {
  const { size, modules } = matrix;
  const pathParts: string[] = [];
  
  for (let row = 0; row < size; row++) {
    for (let col = 0; col < size; col++) {
      if (modules[row]?.[col]) {
        // Draw a 1x1 square at (col + margin, row + margin)
        pathParts.push(`M${col + margin},${row + margin}h1v1h-1z`);
      }
    }
  }
  return pathParts.join('');
}

/**
 * Generates an optimized, valid SVG XML string from a QRCodeMatrix.
 * 
 * @param matrix The QRCodeMatrix generated by `generateQRCode`.
 * @param options Styling and scaling options.
 * @returns A safe SVG XML string.
 */
export function renderToSVGString(matrix: QRCodeMatrix, options: QRCodeSVGOptions = {}): string {
  const { size, modules } = matrix;
  
  const scale = options.scale ?? 4;
  const lightColor = options.color?.light ?? '#ffffff';
  const darkColor = options.color?.dark ?? '#000000';
  const responsive = options.responsive ?? true;

  const margin = options.margin ?? 4;
  const totalSize = size + margin * 2;
  const width = options.width ?? (totalSize * scale);
  const height = width;

  // We optimize SVG paths by drawing all dark modules as a single compound path.
  // This drastically reduces DOM size compared to drawing hundreds of <rect> elements.
  const pathData = buildSVGPath(matrix, margin);

  // Assemble SVG root
  let svg = `<svg xmlns="http://www.w3.org/2000/svg" `;
  svg += `viewBox="0 0 ${totalSize} ${totalSize}" `;
  
  if (!responsive) {
    svg += `width="${width}" height="${height}" `;
  } else {
    // Responsive SVGs typically expand to fit their container.
    // If a strict width/scale was requested even in responsive mode, 
    // the consumer should handle it via CSS on the wrapper.
    svg += `style="width: 100%; height: auto;" `;
  }
  
  svg += `shape-rendering="crispEdges">`;

  // Draw background if not transparent
  if (lightColor.toLowerCase() !== 'transparent') {
    svg += `<rect width="100%" height="100%" fill="${escapeXml(lightColor)}" />`;
  }

  // Draw dark modules path
  if (pathData) {
    svg += `<path d="${pathData}" fill="${escapeXml(darkColor)}" />`;
  }

  svg += `</svg>`;

  return svg;
}
