#!/bin/bash
set -e

echo "========================================"
echo "EXTERNAL CONSUMER VALIDATION"
echo "========================================"

VALIDATION_DIR=".tmp/platform-consumer-validation"
TARBALLS_DIR="$VALIDATION_DIR/tarballs"

if [ ! -d "$TARBALLS_DIR" ]; then
  echo "Error: Tarballs directory $TARBALLS_DIR does not exist. Run platform-validate.sh first."
  exit 1
fi

echo "--- Setting up Node.js Consumer ---"
NODE_CONSUMER_DIR="$VALIDATION_DIR/node-consumer"
rm -rf "$NODE_CONSUMER_DIR"
mkdir -p "$NODE_CONSUMER_DIR"
cd "$NODE_CONSUMER_DIR"

npm init -y > /dev/null
npm install typescript tsx @types/node --save-dev > /dev/null

echo "Installing platform tarballs into Node consumer..."
npm install ../tarballs/skyra-qr-0.1.0.tgz ../tarballs/skyra-utils-0.1.0.tgz ../tarballs/skyra-data-export-0.1.0.tgz ../tarballs/skyra-validation-0.1.0.tgz > /dev/null

cat << 'EOF' > test-esm.mts
import { simpleId } from "@skyra/utils";
import { emailSchema } from "@skyra/validation";
import { exportToCsv } from "@skyra/data-export";
import { generateQRCode } from "@skyra/qr/core";

console.log("ESM @skyra/utils:", simpleId());
console.log("ESM @skyra/validation:", emailSchema.safeParse("test@example.com").success);
console.log("ESM @skyra/data-export:", typeof exportToCsv);
console.log("ESM @skyra/qr/core:", typeof generateQRCode);
EOF

cat << 'EOF' > test-cjs.cts
const { simpleId } = require("@skyra/utils");
const { emailSchema } = require("@skyra/validation");
const dataExport = require("@skyra/data-export");
const { generateQRCode } = require("@skyra/qr/core");

console.log("CJS @skyra/utils:", simpleId());
console.log("CJS @skyra/validation:", emailSchema.safeParse("test@example").success);
console.log("CJS @skyra/data-export:", typeof dataExport.exportToCsv);
console.log("CJS @skyra/qr/core:", typeof generateQRCode);
EOF

cat << 'EOF' > tsconfig.json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ESNext",
    "strict": true,
    "types": ["node"]
  },
  "include": ["test-esm.mts", "test-cjs.cts"]
}
EOF

echo "Running TypeScript check (Node Consumer)..."
npx tsc --noEmit

echo "Running ESM test..."
npx tsx test-esm.mts

echo "Running CJS test..."
npx tsx test-cjs.cts

cd ../../..

echo "--- Setting up Next.js Consumer ---"
NEXT_CONSUMER_DIR="$VALIDATION_DIR/next-consumer"
rm -rf "$NEXT_CONSUMER_DIR"
cd "$VALIDATION_DIR"

echo "Creating Next.js app..."
# Use YES to avoid prompts and force specific options
npx create-next-app@latest next-consumer --typescript --eslint --tailwind --app --src-dir --import-alias "@/*" --use-npm > /dev/null

cd next-consumer

echo "Installing platform tarballs into Next consumer..."
# Expand the list explicitly to avoid shell globbing issues with npm
npm install ../tarballs/skyra-qr-0.1.0.tgz ../tarballs/skyra-ui-0.1.0.tgz ../tarballs/skyra-utils-0.1.0.tgz ../tarballs/skyra-data-export-0.1.0.tgz ../tarballs/skyra-design-tokens-0.1.0.tgz ../tarballs/skyra-data-table-0.1.0.tgz ../tarballs/skyra-dialogs-0.1.0.tgz ../tarballs/skyra-dynamic-form-0.1.0.tgz ../tarballs/skyra-validation-0.1.0.tgz > /dev/null
npm install lucide-react > /dev/null

cat << 'EOF' > src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
EOF

cat << 'EOF' > src/app/page.tsx
import { QRCode } from "@skyra/qr/react";
import { Button } from "@skyra/ui";
import "@skyra/ui/styles.css";

export default function Page() {
  return (
    <div>
      <QRCode value="https://example.com" />
      <Button>Click me</Button>
    </div>
  );
}
EOF

echo "Running TypeScript check (Next.js Consumer)..."
npx tsc --noEmit

echo "Running Next.js build..."
npm run build > /dev/null

cd ../../..

echo "========================================"
echo "EXTERNAL CONSUMER VALIDATION PASSED"
echo "========================================"
